export const market_data_query_string = {
  type: 'object',
  properties: {
    timeStamp: { type: 'string', format: 'date-time' },
    limit: { type: 'number' },
    pageNumber: { type: 'number' },
  },
  required: ['timeStamp', 'limit', 'pageNumber'],
};

export const page_details_schema = {
  current: { type: 'number', nullable: true },
  previous: { type: 'number', nullable: true },
  totalPages: { type: 'number', nullable: true },
  next: {
    type: 'object',
    nullable: true,
    properties: {
      page: { type: 'number' },
      limit: { type: 'number' },
      link: { type: 'string', nullable: true },
    },
  },
};

export const scheme_master_schema = {
  type: 'array',
  items: {
    type: 'object',
    properties: {
      Scheme_Id: { type: 'number' },
      Scheme_Name: { type: 'string' },
      FullName: { type: 'string' },
      AMFI_Name: { type: 'string' },
      AMFI_Code: { type: 'number' },
      AMC_Name: { type: 'string' },
      Initial_NAV: { type: 'number' },
      Inception_Date: { type: 'string', format: 'date-time' },
      Inception_NAV: { type: 'number' },
      Asset_Type: { type: 'string' },
      Type: { type: 'string' },
      Category: { type: 'string' },
      Sub_Category: { type: 'string', nullable: true },
      Scheme_Plan: { type: 'string' },
      Scheme_Option: { type: 'string' },
      SCHEME_ISIN: { type: 'string' },
      Index_Id: { type: 'number', nullable: true },
      Actual_Index_ID: { type: 'number', nullable: true },
      Primary_Fund_Manager: { type: 'string' },
      Second_Fund_manager: { type: 'string', nullable: true },
      Entry_Load: { type: 'number', nullable: true },
      Exit_Load: { type: 'number' },
      Expense_Ratio: { type: 'number' },
      Active_Inactive_Flag: { type: 'boolean' },
      Active_Inactive_Status: { type: 'string', nullable: true },
      Daily_Monthly_Flag: { type: 'number' },
      Min_Investment: { type: 'number' },
      Primary_FM_ID: { type: 'number', nullable: true },
      Second_FM_ID: { type: 'number', nullable: true },
      Display_AMC_Name: { type: 'string' },
      Display_Scheme_Name: { type: 'string' },
      Primary_Flag: { type: 'string' },
      RTA_CODE: { type: 'string' },
      Color_Code: { type: 'string' },
      LockIn_Period: { type: 'number' },
      Load_LockIn: { type: 'string' },
      Redemption_Days: { type: 'number' },
      Price_Earnings: { type: 'number', nullable: true },
      Price_To_Book: { type: 'number', nullable: true },
      SIP_Status: { type: 'string' },
      Div_Reinvest_Flag: { type: 'number' },
      AMC_ID: { type: 'number' },
      maturity_date: { type: 'string', nullable: true, format: 'date-time' },
      Updated_On: { type: 'string', format: 'date-time' },
      Scheme_OD_Name: { type: 'string' },
      Scheme_Tax_Type: { type: 'string' },
      CATEGORY_ID: { type: 'number' },
      Composite_Score: { type: 'number', nullable: true },
      Index_Name: { type: 'string', nullable: true },
      AMC_short_Name: { type: 'string' },
      Exit_Remarks: { type: 'string' },
      AUM: { type: 'number' },
    },
  },
};

export const security_master_schema = {
  type: 'array',
  items: {
    type: 'object',
    properties: {
      CompanyCode: { type: 'number' },
      SecurityTypeCode: { type: 'number' },
      SecuritySubTypeCode: { type: 'number' },
      SerialNumber: { type: 'number' },
      SecurityCode: { type: 'string' },
      TickerName: { type: 'string' },
      IssuePrice: { type: 'number' },
      Description: { type: 'string' },
      DateOfIssue: { type: 'string', format: 'date-time' },
      DateOfExpiry: { type: 'string', nullable: true },
      FaceValue: { type: 'number' },
      MarketLot: { type: 'number' },
      ISINCode: { type: 'string' },
      Remarks: { type: 'string' },
      CreatedOn: { type: 'string' },
      CreatedBy: { type: 'string' },
      LastModifiedOn: { type: 'string' },
      LastModifiedBy: { type: 'string' },
      ReasonForModification: { type: 'string' },
      DeleteFlag: { type: 'boolean' },
      Code: { type: 'string' },
      IsItActiveSecurity: { type: 'boolean' },
      BroadIndustryCode: { type: 'number' },
      BroadIndustryName: { type: 'string' },
      ShortCompanyName: { type: 'string' },
      nsecode: { type: 'string', nullable: true },
    },
  },
};

export const scheme_rapm_schema = {
  type: 'array',
  items: {
    type: 'object',
    properties: {
      RTA_CODE: { type: 'string' },
      Scheme_ID: { type: 'number' },
      From_Date: { type: 'string', format: 'date-time' },
      To_Date: { type: 'string', format: 'date-time' },
      Absolute_PO_Return: { type: 'number' },
      Absolute_BM_Return: { type: 'number' },
      Ann_PO_Return: { type: 'number' },
      Ann_BM_Return: { type: 'number' },
      Alpha: { type: 'number' },
      Portfolio_Volatility: { type: 'number' },
      Benchmark_Volatility: { type: 'number' },
      Beta: { type: 'number' },
      Jenson_Alpha: { type: 'number' },
      PO_Sortino_Ratio: { type: 'number' },
      BM_Sortino_Ratio: { type: 'number' },
      PO_Treynor_Ratio: { type: 'number' },
      BM_Treynor_Ratio: { type: 'number' },
      PO_Sharpe_Ratio: { type: 'number' },
      BM_Sharpe_Ratio: { type: 'number' },
      Active_Risk: { type: 'number' },
      Information_Ratio: { type: 'number' },
      P_RET_1M: { type: 'number' },
      BM_RET_1M: { type: 'number' },
      P_RET_3M: { type: 'number' },
      BM_RET_3M: { type: 'number' },
      P_RET_6M: { type: 'number' },
      BM_RET_6M: { type: 'number' },
      P_RET_1Y: { type: 'number' },
      BM_RET_1Y: { type: 'number' },
      BM_RET_3Y: { type: 'number' },
      P_RET_3Y: { type: 'number' },
      P_RET_5Y: { type: 'number' },
      BM_RET_5Y: { type: 'number' },
      P_RET_2Y: { type: 'number' },
      BM_RET_2Y: { type: 'number' },
      PO_Sharpe_Ratio_1Y: { type: 'number' },
      PO_Sharpe_Ratio_3Y: { type: 'number' },
      PO_Sharpe_Ratio_5Y: { type: 'number' },
      Portfolio_Volatility_1Y: { type: 'number' },
      Portfolio_Volatility_3Y: { type: 'number' },
      Portfolio_Volatility_5Y: { type: 'number' },
      P_Ret_1D: { type: 'number' },
      AUM: { type: 'number', nullable: 'true' },
      BM_Ret_1D: { type: 'number' },
      CAT_RET_1D: { type: 'number' },
    },
  },
};

export const security_prices_schema = {
  type: 'array',
  items: {
    type: 'object',
    properties: {
      PRICEDATE: { type: 'string', format: 'date-time' },
      SECURITYCODE: { type: 'string' },
      ISINCODE: { type: 'string' },
      NSECLOSEPRICE: { type: 'number' },
      BSECLOSEPRICE: { type: 'number' },
      Description: { type: 'string' },
    },
  },
};

export const corporate_action_schema = {
  type: 'array',
  items: {
    type: 'object',
    properties: {
      ROWID: { type: 'string' },
      CATYPE: { type: 'string' },
      BCNUMBER: { type: 'string' },
      COMPANYCODE: { type: 'string' },
      SECURITYNAME: { type: 'string' },
      SECURITYCODE: { type: 'string' },
      BSENSECODE: { type: 'string' },
      ISINCODE: { type: 'string' },
      BCFROMDATE: { type: 'string', format: 'date-time', nullable: 'true' },
      BCTODATE: { type: 'string', format: 'date-time', nullable: 'true' },
      EXDATE: { type: 'string', format: 'date-time' },
      REMARKS: { type: 'string' },
      DIVIDENDRATE: { type: 'number' },
      DIVIDENDPERSHARE: { type: 'number' },
      ADDUPDFLAG: { type: 'string' },
      NEWRATIO: { type: 'number' },
      OLDRATIO: { type: 'number' },
      ISSUEPRICE: { type: 'number' },
      SUBSCRIPTIONSTARTDATE: { type: 'string', format: 'date-time', nullable: 'true' },
      SUBSCRIPTIONENDDATE: { type: 'string', format: 'date-time', nullable: 'true' },
      NOTES: { type: 'string' },
      EXCHANGE: { type: 'string' },
      EFFECTIVEDATE: { type: 'string', format: 'date-time' },
      OLDISIN: { type: 'string' },
      OLDNAME: { type: 'string' },
      PAYDATE: { type: 'number', nullable: 'true' },
      FACEVALUE: { type: 'number' },
      MARKETLOT: { type: 'number' },
      GROUP: { type: 'string' },
      SECURITYTYPE: { type: 'string' },
      SETTLEMENTMODE: { type: 'string' },
      LASTMODIFIED: { type: 'string', format: 'date-time' },
      VESTEDCOMPANYNAME: { type: 'string', nullable: 'true' },
      VESTEDCOMPANYCODE: { type: 'string', nullable: 'true' },
      VESTEDSECURITYCODE: { type: 'string', nullable: 'true' },
      VESTEDSECURITYISIN: { type: 'string', nullable: 'true' },
      MAINCOMPANY_RATIOEXIST: { type: 'string', nullable: 'true' },
      ACQUIRERCOMPANYCODE: { type: 'string', nullable: 'true' },
      ACQUIRERSECURITYCODE: { type: 'string', nullable: 'true' },
      ACQUIRERCOMPANYNAME: { type: 'string', nullable: 'true' },
      ACQUIREECOMPANYCODE: { type: 'string', nullable: 'true' },
      ACQUIREESECURITYCODE: { type: 'string', nullable: 'true' },
      ACQUIREECOMPANYNAME: { type: 'string', nullable: 'true' },
      MERGERDESCRIPTION: { type: 'string', nullable: 'true' },
    },
  },
};

export const holdings_wf = {
  type: 'array',
  items: {
    type: 'object',
    properties: {
      SCHEME_ID: { type: 'number' },
      RTA_CODE: { type: 'string' },
      HOLDING_DATE: { type: 'string', format: 'date-time' },
      SECURITY_ISIN: { type: 'string' },
      RATING: { type: 'string' },
      ASSET_TYPE: { type: 'string' },
      INSTRUMENT_NAME: { type: 'string' },
      ASSET: { type: 'string' },
      ASSET_CLASSIFICATION: { type: 'string' },
      HOLDINGSINPERC: { type: 'string' },
      CORPOUS: { type: 'number' },
      GICS_SECTOR: { type: 'string' },
      MODIFIED_DATE: { type: 'string', format: 'date-time' },
      MTM_VALUE: { type: 'number' },
      INDUSTRY: { type: 'string' },
      RATING_CLASS_VF: { type: 'string' },
      Rating_Classification: { type: 'string' },
      maturity_date: { type: 'string', format: 'date-time' },
      Asset_Type_Wealthfy: { type: 'string' },
      SECURITIES: { type: 'string' },
    },
  },
};
